name: Dispatch OpenAPI File Change event
on:
  push:
    branches: 
      - main
    paths:
      - "petstore.yaml"

jobs:
  dispatch:
    env:
      APP_SERVICES_CI_TOKEN: ${{ secrets.GH_CI_TOKEN }}
    strategy:
      matrix:
        repo:
          - "redhat-developer/app-services-sdk-go"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: main
          list-files: json
          filters: |
            openapi:
              - 'openapi/*.yaml'
      - if: contains(steps.filter.outputs.openapi_files, 'petstore.yaml')
        name: Petstore OpenAPI changed
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ env.APP_SERVICES_CI_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: openapi-spec-change
          client-payload: '{ "id": "petstore-mgmt/v1", "download_url":"https://raw.githubusercontent.com/craicoverflow/petstore-openapi/main/petstore.yaml"}'
